development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: db_dev
  pool: 5
  username: pguser
  password: pguser_password

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: db_test
  pool: 5
  timeout: 5000
  username: pguser
  password: pguser_password

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
